### ISSUE TITLE
Error when installing from master branch

### ISSUE THREAD

**Issue by razman786** [GauiStori/PyQt-Qwt#20]
Hi Gudjon

When running the following `QT_SELECT=qt5 python3 configure.py --qwt-incdir=/usr/include/qwt --qwt-libdir=/usr/lib --qwt-lib=qwt-qt5` on Ubuntu 20.04 with Qwt 6.1.4 or Gentoo with Qwt 6.1.5, I get the following error:

```python
An internal error occured.  Please report all the output from the program,
including the following traceback, to gudjon@gudjon.org.
Traceback (most recent call last):
  File "configure.py", line 2067, in <module>
    _main(sys.argv, pkg_config)
  File "configure.py", line 1909, in _main
    pkg_config.check_package(target_config)
  File "configure.py", line 245, in check_module
    mod_version_numeric = int(mv[0])*10000 + int(mv[1])*100 + int(mv[2])
ValueError: invalid literal for int() with base 10: '0beta0'
```
If I remove 'beta' from the following, then everything compiles and works fine:
```python
configure.py:    version = '2.0.0beta0'
```
Cheers,
Raz

**Comment by razman786** [comment]
Thank you for fixing this 🙂 I'll close the issue.
